name: Move Project Column Action
description:
  This Action moves an issue to a specified column in a GitHub V2 Project.
author: stulle123
branding:
  icon: thumbs-up
  color: blue

inputs:
  github-token:
    description: GitHub token
    required: true
  issue-number:
    description: Issue number
    required: true
  project-number:
    description: Project number
    required: true
  column-name:
    description: Column name
    required: true
  repo-name:
    description: Repository name
    required: false
  repo-owner:
    description: Repository owner
    required: false

runs:
  using: node24
  main: dist/index.js
